import { useEffect, useState } from 'react'
import { NavLink, Route, Routes } from 'react-router-dom'
import { competitors, insights, matrix, recentCompetitorUpdates, releaseItems } from './demo-data'
import { supabase } from './supabase'

const nav = [['/', 'Market intelligence', ''], ['/competitors', 'Competitors', '40'], ['/matrix', 'Capability matrix', ''], ['/release-watch', 'Release Watch', '3'], ['/automation', 'Automation', ''], ['/claim-lens', 'Claim Lens', ''], ['/ask', 'Ask TestOrbit', '']]
const badgeClass = (value: string) => value.toLowerCase().replaceAll(' ', '-')
const LIVE_API = 'https://testorbit-api.onrender.com/api/v1/intelligence/today'
type LiveSignal = { id: string; competitor: string; title: string; summary: string; evidence_status: string; source_url: string; confidence: number; fact: string; inference?: string; first_detected_date: string }
type LiveBrief = { headline: string; signals: LiveSignal[]; source_scope: string }
type WorkspaceCompetitor = { name: string; category: string; focus: string; changed: number }
const COMPETITOR_STORAGE_KEY = 'testorbit-workspace-competitors'
type AutomationSchedule = { time: string; frequency: 'daily' | 'weekdays' | 'weekly'; day: string; slack: boolean }
type SharedSchedule = { frequency: AutomationSchedule['frequency']; day_of_week: string; time_ist: string; slack_enabled: boolean; last_run_date: string | null; timezone: string }
const greetingForTime = () => { const hour = new Date().getHours(); if (hour < 12) return 'Good morning'; if (hour < 18) return 'Good afternoon'; return 'Good evening' }

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="shell"><aside className="side-nav"><div className="brand"><span className="orbit" /> ORBIT</div><nav><p className="workspace">RESEARCH WORKSPACE</p>{nav.map(([to, label, count]) => <NavLink key={to} to={to} end={to === '/'}><span className={to === '/' ? 'nav-dot' : ''} />{label}{count && <b>{count}</b>}</NavLink>)}</nav><div className="evidence-ledger"><p>EVIDENCE LEDGER</p><div><span>Verified official</span><b>5</b></div><div><span>Marketing claim</span><b>1</b></div><div><span>Synthetic demo</span><b>0</b></div></div><div className="profile"><span>KG</span><div><b>Kavita Gurung</b><small>Research workspace</small></div></div></aside><main><header><div><p className="eyebrow">DAILY RECAP · EVIDENCE-FIRST</p><h1>{greetingForTime()}, Kavita.</h1><p className="header-summary">Here’s your daily recap of what’s happening in the test automation industry. Every signal below separates <b>fact</b> from <i>inference</i>.</p></div><div className="header-actions"><button className="quiet">Last 90 days⌄</button><NavLink className="ask-link" to="/ask">Ask TestOrbit</NavLink></div></header>{children}</main></div>
}

function LiveBriefPanel() {
  const [brief, setBrief] = useState<LiveBrief | null>(null)
  const [error, setError] = useState(false)
  const [period, setPeriod] = useState('30')
  useEffect(() => { fetch(LIVE_API).then((response) => response.ok ? response.json() : Promise.reject()).then(setBrief).catch(() => setError(true)) }, [])
  if (error) return <section className="live-brief panel"><p className="eyebrow">OFFICIAL-SOURCE INTELLIGENCE</p><p className="muted">Live intelligence is temporarily unavailable. Synthetic demo data remains visible below.</p></section>
  if (!brief) return <section className="live-brief panel"><p className="eyebrow">OFFICIAL-SOURCE INTELLIGENCE</p><p className="muted">Loading verified competitor evidence…</p></section>
  const visibleSignals = brief.signals.filter((signal) => { if (period === 'all') return true; const end = new Date(); end.setHours(23, 59, 59, 999); const start = new Date(end); start.setDate(start.getDate() - Number(period)); const detected = new Date(`${signal.first_detected_date}T00:00:00`); return detected >= start && detected <= end })
  return <section className="live-brief panel"><div className="panel-heading"><div><p className="eyebrow">OFFICIAL-SOURCE INTELLIGENCE · BETA</p><h2>{brief.headline}</h2></div><label className="period-label">Date range<select value={period} onChange={(event) => setPeriod(event.target.value)}><option value="0">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All verified</option></select></label></div><p className="muted">{brief.source_scope} Showing evidence first detected in the selected period.</p><div className="live-signals">{visibleSignals.map(signal => <article key={signal.id}><p className="signal-meta">{signal.competitor} · confidence {signal.confidence}%</p><h3>{signal.title}</h3><p>{signal.summary}</p><span className="badge">{signal.evidence_status}</span><p><b>Fact:</b> {signal.fact}</p>{signal.inference && <p className="muted"><b>Inference:</b> {signal.inference}</p>}<a href={signal.source_url} target="_blank" rel="noreferrer">View official evidence</a></article>)}</div></section>
}

function AIInsights() {
  const [filter, setFilter] = useState('All Insights')
  const [range, setRange] = useState('90')
  const visible = insights.filter(i => i.subjectType === 'Competitor' && (filter === 'All Insights' || filter === 'Competitor Moves' || (filter === 'AI and Agentic Testing' && i.category === 'AI announcement') || (filter === 'Deprecations' && i.category === 'Deprecation')) && (range === 'all' || new Date(i.publishedAt) >= new Date(Date.now() - Number(range) * 86400000)))
  return <section className="panel ai-insights"><div className="panel-heading"><div><p className="eyebrow">OFFICIAL-SOURCE COMPETITOR INTELLIGENCE · LIVE SEED</p><h2>New market competitor updates</h2><p className="muted">{visible.length ? `${visible.length} verified competitor updates found in the selected period.` : 'No verified competitor updates were found in the selected period.'}</p></div><div className="insight-filters"><select value={filter} onChange={e => setFilter(e.target.value)}>{['All Insights','Competitor Moves','AI and Agentic Testing','Pricing and Packaging','Integrations','ERP Coverage','CI/CD','Deprecations'].map(x => <option key={x}>{x}</option>)}</select><select value={range} onChange={e => setRange(e.target.value)}><option value="1">Last 24 hours</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All verified</option></select></div></div><div className="insight-grid">{visible.map(i => <article key={i.id}><p className="eyebrow">NEW MARKET COMPETITOR UPDATE</p><p className="signal-meta">{i.subject} · {i.category}</p><h3>{i.headline}</h3><p><b>Fact:</b> {i.fact}</p><p><b>Inference:</b> {i.inference}</p><p><b>Recommended investigation:</b> {i.recommendation}</p><p className="muted">Published {i.publishedAt} · First detected {i.firstDetectedAt} · Last verified {i.lastVerifiedAt}</p><span className="badge">{i.evidenceStatus} · {i.confidence}%</span><a href={i.sourceUrl} target="_blank" rel="noreferrer">View official evidence</a></article>)}</div></section>
}
function DashboardRail() { return <aside className="dashboard-rail"><section><p className="rail-label">COVERAGE TODAY</p><div className="coverage-grid">{[['5','Verified insights'],[String(competitors.length),'Competitors watched'],['3','Release platforms'],['0','Validation queue']].map(([value, label]) => <div key={label}><b>{value}</b><span>{label}</span></div>)}</div></section><section><p className="rail-label">SOURCES CHECKED</p>{['UiPath release notes','Opkey newsroom','Functionize newsroom','Tricentis release notes'].map((source) => <div className="source-row" key={source}><i />{source}<span>09:00</span></div>)}<p className="rail-note">Collection monitors public official sources. A release notice alone does not prove a selector change.</p></section><section className="ask-card"><p>ASK TESTORBIT</p><strong>Which agentic-testing claims still lack independent validation?</strong><NavLink to="/ask">Run this question</NavLink></section></aside> }
function Dashboard() { return <div className="dashboard-layout"><div className="dashboard-content"><AIInsights/><LiveBriefPanel/><section className="metrics">{[['Verified AI Insights', '5','official sources only'],['Configured competitors',String(competitors.length),'including market signals'],['Release platforms','3','Workday, ServiceNow, SAP SuccessFactors'],['Validation queue','0','no synthetic claims promoted']].map(([label, value, hint]) => <article key={label}><p>{label}<span title={hint}>i</span></p><strong>{value}</strong><small>{hint}</small></article>)}</section><section className="panel feed"><div className="panel-heading"><div><p className="eyebrow">RECENT COMPETITOR UPDATES · OFFICIAL SOURCES</p><h2>What changed in the last 30 days</h2><p className="muted">Five recent official publications from test-automation competitors. Open each source to review the original evidence.</p></div></div>{recentCompetitorUpdates.map(update => <article className="signal real-signal" key={update.id}><div className="signal-dot"/><div><p className="signal-meta">{update.vendor} · {update.category} · {update.date}</p><h3>{update.title}</h3><p>{update.summary}</p><span className="badge">{update.evidenceStatus}</span><a href={update.sourceUrl} target="_blank" rel="noreferrer">Source: {update.sourceName} →</a></div></article>)}</section></div><DashboardRail/></div> }

function Competitors() {
  const [items, setItems] = useState<WorkspaceCompetitor[]>(() => { try { return JSON.parse(localStorage.getItem(COMPETITOR_STORAGE_KEY) || '') } catch { return competitors } })
  const [name, setName] = useState('')
  const [category, setCategory] = useState('Direct competitor')
  const [focus, setFocus] = useState('Test automation')
  const addCompetitor = (event: React.FormEvent) => { event.preventDefault(); const cleaned = name.trim(); if (!cleaned || items.some((item) => item.name.toLowerCase() === cleaned.toLowerCase())) return; const next = [...items, { name: cleaned, category, focus: focus.trim() || 'Unknown', changed: 0 }]; setItems(next); localStorage.setItem(COMPETITOR_STORAGE_KEY, JSON.stringify(next)); setName(''); setFocus('Test automation') }
  return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">EDITABLE DIRECTORY</p><h2>Competitor profiles</h2><p className="muted">Changes are saved in this browser. Shared, audited competitor management will be added with the persistent workspace database.</p></div></div><form className="competitor-form" onSubmit={addCompetitor}><input aria-label="Competitor name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Competitor or framework name" required /><select aria-label="Competitor category" value={category} onChange={(event) => setCategory(event.target.value)}><option>Direct competitor</option><option>Enterprise competitor</option><option>ERP specialist</option><option>AI-native competitor</option><option>Developer-first alternative</option><option>Market signal only</option></select><input aria-label="Competitor focus" value={focus} onChange={(event) => setFocus(event.target.value)} placeholder="Focus or product area" /><button className="primary" type="submit">Add competitor</button></form><div className="directory">{items.map(c => <article key={c.name}><div className="avatar">{c.name.slice(0,2)}</div><div><h3>{c.name}</h3><p>{c.category} · {c.focus}</p></div><span className="count">{c.changed} recent signals</span></article>)}</div></section>
}
function ReleaseWatch() {
  const [range, setRange] = useState('30')
  const [platform, setPlatform] = useState('All Platforms')
  const visible = releaseItems.filter(item => platform === 'All Platforms' || item.platform === platform)
  return <section className="release-watch"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">OFFICIAL RELEASE INTELLIGENCE</p><h2>Release Watch</h2><p className="muted">Public official sources only. Workday detailed tenant release notes are not accessed; coverage is limited to accessible official publications.</p></div><label className="period-label">Review period<select value={range} onChange={(event) => setRange(event.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></label></div><div className="platform-tabs">{['All Platforms','Workday','ServiceNow','SAP SuccessFactors'].map(x => <button className={platform === x ? 'active' : ''} onClick={() => setPlatform(x)} key={x}>{x}</button>)}</div><div className="watch-grid">{visible.map(item => <article key={item.id}><div className="watch-title"><div className="avatar">{item.platform.slice(0,2)}</div><div><h3>{item.platform}</h3><p>{item.category} · {item.family}</p></div></div><h3>{item.title}</h3><dl><div><dt>Published / detected / verified</dt><dd>{item.publishedAt} / {item.firstDetectedAt} / {item.lastVerifiedAt}</dd></div><div><dt>Product changes</dt><dd>{item.changes}</dd></div><div><dt>Potential testing impact</dt><dd>{item.impact}</dd></div><div><dt>Affected areas</dt><dd>{item.areas}</dd></div></dl><span className="watch-status">{item.evidenceStatus} · {item.confidence}% · {item.sourceHealth}</span><a href={item.sourceUrl} target="_blank" rel="noreferrer">View official evidence</a></article>)}</div></div><section className="panel monitor-flow"><p className="eyebrow">SOURCE HEALTH</p><h2>Evidence before alerting</h2><p className="muted">Last collection, retry state, and stale-source warnings are recorded by the live collector. A release publication alone is not a selector-breakage claim; selector risk requires evidence from an authorized test environment.</p></section></section>
}

function Automation() {
  const [schedule, setSchedule] = useState<AutomationSchedule>({ time: '09:00', frequency: 'daily', day: 'Monday', slack: true })
  const [accessToken, setAccessToken] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [message, setMessage] = useState('')
  const api = 'https://testorbit-api.onrender.com/api/v1/automation'
  const loadSchedule = () => fetch(`${api}/schedule`).then(response => response.ok ? response.json() : Promise.reject()).then((value: SharedSchedule) => setSchedule({ frequency: value.frequency, day: value.day_of_week, time: value.time_ist, slack: value.slack_enabled })).catch(() => setMessage('Schedule is temporarily unavailable.'))
  useEffect(() => { loadSchedule(); if (!supabase) return; supabase.auth.getSession().then(({ data }) => setAccessToken(data.session?.access_token || '')); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => setAccessToken(session?.access_token || '')); return () => listener.subscription.unsubscribe() }, [])
  const signIn = async (event: React.FormEvent) => { event.preventDefault(); if (!supabase) return; const { error } = await supabase.auth.signInWithPassword({ email, password }); setMessage(error ? error.message : 'Signed in. You can now save the shared schedule.') }
  const signUp = async () => {
    if (!email || !password) {
      setMessage('Enter your owner email and a password (at least 6 characters) before creating the account.')
      return
    }
    if (!supabase) return
    const { error } = await supabase.auth.signUp({ email, password, options: { emailRedirectTo: 'https://kavitagurung.github.io/TestOrbit/' } })
    setMessage(error ? error.message : 'Account created. Check your email to confirm it, then sign in.')
  }
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!accessToken) { setMessage('Sign in as the workspace owner to apply this schedule.'); return } const response = await fetch(`${api}/schedule`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${accessToken}` }, body: JSON.stringify({ frequency: schedule.frequency, day_of_week: schedule.day, time_ist: schedule.time, slack_enabled: schedule.slack }) }); setMessage(response.ok ? 'Shared cloud schedule saved. It will be checked every 15 minutes.' : (await response.json().catch(() => ({ detail: 'Unable to save schedule.' }))).detail) }
  const runNow = async () => { if (!accessToken) { setMessage('Sign in as the workspace owner to run now.'); return } const response = await fetch(`${api}/run`, { method: 'POST', headers: { Authorization: `Bearer ${accessToken}` } }); setMessage(response.ok ? 'Collection started. Slack will receive the configured digest.' : (await response.json().catch(() => ({ detail: 'Unable to start collection.' }))).detail) }
  return <section className="automation"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">OWNER-CONTROLLED NOTIFICATION</p><h2>Automation schedule</h2><p className="muted">Set the shared collection time in IST. TestOrbit checks this schedule every 15 minutes and sends Slack only when it is due.</p></div><span className="watch-status">{accessToken ? 'Owner signed in' : 'Owner sign-in required'}</span></div><form className="schedule-form" onSubmit={save}><label>Frequency<select value={schedule.frequency} onChange={(event) => setSchedule({ ...schedule, frequency: event.target.value as AutomationSchedule['frequency'] })}><option value="daily">Every day</option><option value="weekdays">Weekdays</option><option value="weekly">Once a week</option></select></label>{schedule.frequency === 'weekly' && <label>Day<select value={schedule.day} onChange={(event) => setSchedule({ ...schedule, day: event.target.value })}>{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map(day => <option key={day}>{day}</option>)}</select></label>}<label>Time (IST)<input type="time" value={schedule.time} onChange={(event) => setSchedule({ ...schedule, time: event.target.value })} /></label><label className="toggle-row"><input type="checkbox" checked={schedule.slack} onChange={(event) => setSchedule({ ...schedule, slack: event.target.checked })} /><span>Send a Slack digest</span></label><button className="primary" type="submit">Apply schedule</button></form><button className="quiet run-now" onClick={runNow}>Run collection now</button>{message && <p className="save-note">{message}</p>}</section>{!accessToken && <section className="panel"><p className="eyebrow">OWNER SIGN-IN</p><h2>Secure the schedule</h2>{supabase ? <form className="signin-form" onSubmit={signIn}><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Owner email" required /><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password" required /><button className="primary" type="submit">Sign in</button><button className="quiet" type="button" onClick={signUp}>Create owner account</button></form> : <p className="muted">Supabase Auth public settings have not been added to this deployment yet.</p>}</section>}<section className="panel"><p className="eyebrow">CURRENT CLOUD AUTOMATION</p><h2>How it runs</h2><div className="automation-status"><div><b>GitHub Actions</b><span>Checks the owner’s shared schedule every 15 minutes</span></div><strong>IST</strong></div><p className="muted">Only the configured Supabase owner can change the schedule. Slack webhook details and scheduler credentials remain server-side.</p></section></section>
}
function Matrix() { return <section className="panel"><p className="eyebrow">EVIDENCE-BACKED SUPPORT</p><h2>Capability matrix</h2><p className="muted">“Not found” means evidence was not found; it does not mean unsupported.</p><div className="table-wrap"><table><thead><tr><th>Capability</th><th>NovaTest</th><th>VerityQA</th><th>OrbitSpec</th></tr></thead><tbody>{matrix.map(row => <tr key={row[0]}>{row.map((cell, i) => <td key={cell}>{i ? <span className={`cell ${badgeClass(cell)}`}>{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div></section> }
function ClaimLens() { return <section className="panel claim"><p className="eyebrow">MARKETING-CLAIM INTELLIGENCE</p><h2>Claim Lens</h2><blockquote>“Autonomous testing for every enterprise workflow.”</blockquote><div className="claim-grid"><div><p>Classification</p><strong>Marketing-level claim</strong></div><div><p>Documentation evidence</p><strong>Not found in demo sources</strong></div><div><p>Recommended action</p><strong>Requires validation</strong></div></div><p className="muted">TestOrbit uses neutral, evidence-based labels and does not make accusations about vendor claims.</p></section> }
function Ask() { return <section className="ask"><p className="eyebrow">GROUNDED Q&A</p><h2>Ask TestOrbit</h2><p>Answers cite stored evidence, distinguish facts from inference, and state when information is insufficient.</p><div className="question">Which synthetic competitors have documented AI capabilities?<button className="primary">Ask</button></div><div className="answer"><p className="eyebrow">ANSWER · SYNTHETIC DEMO</p><p><b>Fact:</b> NovaTest has one confirmed synthetic announcement for guided AI test planning. VerityQA has no stored AI-capability evidence in this demo’s current date range.</p><p><b>Inference:</b> Evidence is insufficient to compare broader AI maturity.</p><a href="#sig-001">Citation: SIG-001 · 30 Jul 2026</a></div></section> }

export default function App() { return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/competitors" element={<Competitors/>}/><Route path="/matrix" element={<Matrix/>}/><Route path="/release-watch" element={<ReleaseWatch/>}/><Route path="/automation" element={<Automation/>}/><Route path="/claim-lens" element={<ClaimLens/>}/><Route path="/ask" element={<Ask/>}/></Routes></Shell> }
