import { useEffect, useState } from 'react'
import { NavLink, Route, Routes } from 'react-router-dom'
import { competitors, matrix, signals } from './demo-data'

const nav = [['/', 'Market intelligence'], ['/competitors', 'Competitors'], ['/matrix', 'Capability matrix'], ['/claim-lens', 'Claim Lens'], ['/ask', 'Ask TestOrbit']]
const badgeClass = (value: string) => value.toLowerCase().replaceAll(' ', '-')
const LIVE_API = 'https://testorbit-api.onrender.com/api/v1/intelligence/today'
type LiveSignal = { id: string; competitor: string; title: string; summary: string; evidence_status: string; source_url: string; confidence: number; fact: string; inference?: string }
type LiveBrief = { headline: string; signals: LiveSignal[]; source_scope: string }

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="shell"><aside><div className="brand"><span className="orbit" /> TEST<span>ORBIT</span></div><p className="workspace">SYNTHETIC DEMO WORKSPACE</p><nav>{nav.map(([to, label]) => <NavLink key={to} to={to} end={to === '/'}>{label}</NavLink>)}</nav><div className="security-note">All signals are synthetic demonstration data. Evidence and inference are deliberately separated.</div></aside><main><header><div><p className="eyebrow">TODAY · 01 AUG 2026</p><h1>Competitive intelligence, grounded in evidence.</h1></div><button className="quiet">Demo mode</button></header>{children}</main></div>
}

function LiveBriefPanel() {
  const [brief, setBrief] = useState<LiveBrief | null>(null)
  const [error, setError] = useState(false)
  useEffect(() => { fetch(LIVE_API).then((response) => response.ok ? response.json() : Promise.reject()).then(setBrief).catch(() => setError(true)) }, [])
  if (error) return <section className="live-brief panel"><p className="eyebrow">OFFICIAL-SOURCE INTELLIGENCE</p><p className="muted">Live intelligence is temporarily unavailable. Synthetic demo data remains visible below.</p></section>
  if (!brief) return <section className="live-brief panel"><p className="eyebrow">OFFICIAL-SOURCE INTELLIGENCE</p><p className="muted">Loading verified competitor evidence…</p></section>
  return <section className="live-brief panel"><p className="eyebrow">OFFICIAL-SOURCE INTELLIGENCE · BETA</p><h2>{brief.headline}</h2><p className="muted">{brief.source_scope}</p><div className="live-signals">{brief.signals.map(signal => <article key={signal.id}><p className="signal-meta">{signal.competitor} · confidence {signal.confidence}%</p><h3>{signal.title}</h3><p>{signal.summary}</p><span className="badge">{signal.evidence_status}</span><p><b>Fact:</b> {signal.fact}</p>{signal.inference && <p className="muted"><b>Inference:</b> {signal.inference}</p>}<a href={signal.source_url} target="_blank" rel="noreferrer">View official evidence</a></article>)}</div></section>
}

function Dashboard() { return <><LiveBriefPanel/><section className="metrics">{[['Market activity','24','+18% vs. prior 7 days'],['High-priority signals','3','≥ 75 importance score'],['New AI claims','2','1 confirmed by evidence'],['Validation queue','4','requires PM review']].map(([label, value, hint]) => <article key={label}><p>{label}<span title={hint}>i</span></p><strong>{value}</strong><small>{hint}</small></article>)}</section><section className="grid"><div className="panel feed"><div className="panel-heading"><div><p className="eyebrow">SYNTHETIC DEMO SIGNAL FEED</p><h2>What changed</h2></div><button className="text-button">View all</button></div>{signals.map(s => <article className="signal" key={s.id}><div className="signal-dot"/><div><p className="signal-meta">{s.vendor} · {s.category} · {s.date}</p><h3>{s.title}</h3><p>{s.excerpt}</p><div><span className="badge">{s.status}</span><span className="score">Importance {s.score}</span></div></div></article>)}</div><div className="panel"><p className="eyebrow">MARKET PATTERN</p><h2>Agentic language is rising</h2><div className="trend"><i style={{height: '25%'}}/><i style={{height: '44%'}}/><i style={{height: '37%'}}/><i style={{height: '70%'}}/><i style={{height: '92%'}}/></div><p className="muted">Two independently supported synthetic signals reference guided or human-reviewed AI workflows. This is an observation, not a market conclusion.</p><hr/><p className="eyebrow">RECOMMENDED QUESTION</p><h3>Where does human approval materially improve trust?</h3><button className="primary">Investigate capability gap</button></div></section></> }

function Competitors() { return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">EDITABLE DIRECTORY</p><h2>Competitor profiles</h2></div><button className="primary">Add competitor</button></div><div className="directory">{competitors.map(c => <article key={c.name}><div className="avatar">{c.name.slice(0,2)}</div><div><h3>{c.name}</h3><p>{c.category} · {c.focus}</p></div><span className="count">{c.changed} recent signals</span></article>)}</div></section> }
function Matrix() { return <section className="panel"><p className="eyebrow">EVIDENCE-BACKED SUPPORT</p><h2>Capability matrix</h2><p className="muted">“Not found” means evidence was not found; it does not mean unsupported.</p><div className="table-wrap"><table><thead><tr><th>Capability</th><th>NovaTest</th><th>VerityQA</th><th>OrbitSpec</th></tr></thead><tbody>{matrix.map(row => <tr key={row[0]}>{row.map((cell, i) => <td key={cell}>{i ? <span className={`cell ${badgeClass(cell)}`}>{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div></section> }
function ClaimLens() { return <section className="panel claim"><p className="eyebrow">MARKETING-CLAIM INTELLIGENCE</p><h2>Claim Lens</h2><blockquote>“Autonomous testing for every enterprise workflow.”</blockquote><div className="claim-grid"><div><p>Classification</p><strong>Marketing-level claim</strong></div><div><p>Documentation evidence</p><strong>Not found in demo sources</strong></div><div><p>Recommended action</p><strong>Requires validation</strong></div></div><p className="muted">TestOrbit uses neutral, evidence-based labels and does not make accusations about vendor claims.</p></section> }
function Ask() { return <section className="ask"><p className="eyebrow">GROUNDED Q&A</p><h2>Ask TestOrbit</h2><p>Answers cite stored evidence, distinguish facts from inference, and state when information is insufficient.</p><div className="question">Which synthetic competitors have documented AI capabilities?<button className="primary">Ask</button></div><div className="answer"><p className="eyebrow">ANSWER · SYNTHETIC DEMO</p><p><b>Fact:</b> NovaTest has one confirmed synthetic announcement for guided AI test planning. VerityQA has no stored AI-capability evidence in this demo’s current date range.</p><p><b>Inference:</b> Evidence is insufficient to compare broader AI maturity.</p><a href="#sig-001">Citation: SIG-001 · 30 Jul 2026</a></div></section> }

export default function App() { return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/competitors" element={<Competitors/>}/><Route path="/matrix" element={<Matrix/>}/><Route path="/claim-lens" element={<ClaimLens/>}/><Route path="/ask" element={<Ask/>}/></Routes></Shell> }
