export type Signal = { id: string; vendor: string; title: string; category: string; date: string; confidence: number; status: string; score: number; excerpt: string }
export type Competitor = { name: string; category: string; focus: string; website: string; changed: number; sourceHealth: 'Healthy' | 'Not checked' }
export type Insight = { id: string; subject: string; subjectType: 'Enterprise Application' | 'Competitor'; category: string; headline: string; fact: string; inference: string; recommendation: string; sourceName: string; sourceUrl: string; publishedAt: string; firstDetectedAt: string; lastVerifiedAt: string; confidence: number; evidenceStatus: string; capabilities: string[] }
export type ReleaseItem = { id: string; platform: 'Workday' | 'ServiceNow' | 'SAP SuccessFactors'; title: string; family: string; publishedAt: string; firstDetectedAt: string; lastVerifiedAt: string; category: string; summary: string; changes: string; impact: string; areas: string; confidence: number; evidenceStatus: string; sourceName: string; sourceUrl: string; sourceHealth: string }

export const signals: Signal[] = [
  { id: 'sig-001', vendor: 'NovaTest', title: 'Announced guided AI test planning', category: 'New AI capability', date: '2026-07-30', confidence: 92, status: 'Synthetic demo evidence', score: 88, excerpt: 'Synthetic release note describes guided test-plan generation with human review.' },
  { id: 'sig-002', vendor: 'VerityQA', title: 'Added synthetic Workday coverage', category: 'New ERP support', date: '2026-07-27', confidence: 84, status: 'Synthetic demo evidence', score: 81, excerpt: 'Synthetic documentation now lists Workday among enterprise application examples.' },
  { id: 'sig-003', vendor: 'OrbitSpec', title: 'Changed trial messaging', category: 'Trial change', date: '2026-07-24', confidence: 68, status: 'Synthetic demo evidence', score: 56, excerpt: 'Synthetic pricing page changed from “start free” to “request access”.' },
  { id: 'sig-004', vendor: 'NovaTest', title: 'Published CI workflow connector', category: 'New integration', date: '2026-07-21', confidence: 89, status: 'Synthetic demo evidence', score: 76, excerpt: 'Synthetic integration guide describes pipeline-result artifacts.' },
]

export type RecentCompetitorUpdate = { id: string; vendor: string; category: string; date: string; title: string; summary: string; sourceName: string; sourceUrl: string; evidenceStatus: string }

// Official competitor publications only. These entries are deliberately kept
// separate from synthetic demo data and link directly to the publisher.
export const recentCompetitorUpdates: RecentCompetitorUpdate[] = [
  { id: 'functionize-studio', vendor: 'Functionize', category: 'Product release', date: '2026-07-16', title: 'Functionize Studio is generally available', summary: 'Functionize describes Studio as an adversarial agent for proving software quality at agent speed.', sourceName: 'Functionize official blog', sourceUrl: 'https://www.functionize.com/blog/meet-functionize-studio', evidenceStatus: 'Verified official source' },
  { id: 'uipath-agents-july', vendor: 'UiPath', category: 'AI capability', date: '2026-07-24', title: 'New assignment criteria for agent escalations', summary: 'UiPath documents workload, group, round-robin, and LLM-inferred routing options for agent escalations.', sourceName: 'UiPath Agents release notes', sourceUrl: 'https://docs.uipath.com/agents/automation-cloud/latest/release-notes/july-2026', evidenceStatus: 'Verified official source' },
  { id: 'uipath-test-manager', vendor: 'UiPath', category: 'Preview capability', date: '2026-07-15', title: 'Test with Coding Agents is listed as preview', summary: 'UiPath documents terminal-driven access to Test Manager test cases, results, coverage, and test-set execution.', sourceName: 'UiPath July release notes', sourceUrl: 'https://docs.uipath.com/release-notes/other/latest/release-notes/cloud-platform-july-2026', evidenceStatus: 'Verified official source' },
  { id: 'tricentis-tosca', vendor: 'Tricentis', category: 'Product update', date: 'July 2026', title: 'Generate API messages with a prompt', summary: 'Tosca Cloud’s July release notes describe prompt-based API-message generation through MCP.', sourceName: 'Tricentis Tosca Cloud release notes', sourceUrl: 'https://docs.tricentis.com/tosca-cloud/en-us/content/release_notes/release_notes.htm', evidenceStatus: 'Verified official source' },
  { id: 'opkey-workday-ai', vendor: 'Opkey', category: 'Official market update', date: '2026-07-09', title: 'Opkey published its view on AI-enabled Workday testing', summary: 'Opkey’s official blog describes its perspective on AI-driven Workday testing and ERP lifecycle testing.', sourceName: 'Opkey official blog', sourceUrl: 'https://www.opkey.com/blog/leveraging-ai-in-workday-testing-ensuring-quality-and-efficiency', evidenceStatus: 'Official publication — positioning claim' },
]

const grouped = [
  ['Direct competitors', ['Opkey', 'UiPath', 'Functionize', 'testRigor', 'Tricentis Tosca', 'Tricentis Testim']],
  ['Enterprise and ERP competitors', ['Worksoft', 'Leapwork', 'Panaya', 'Qualibrate', 'Provar', 'Copado Robotic Testing']],
  ['AI-native competitors', ['ACCELQ', 'Testsigma', 'mabl', 'KaneAI', 'Avo Automation', 'Autify', 'Momentic']],
  ['Testing infrastructure', ['BrowserStack', 'Sauce Labs', 'SmartBear TestComplete', 'OpenText UFT One', 'Ranorex', 'Perfecto', 'Kobiton', 'TestGrid', 'Keysight Eggplant', 'LambdaTest', 'Applitools']],
  ['Specialist platforms', ['Katalon', 'Virtuoso', 'Reflect', 'Rainforest QA', 'QA Wolf']],
  ['Developer-first market signals', ['Playwright', 'Cypress', 'Selenium', 'Appium', 'Puppeteer']],
] as const

const slugs: Record<string, string> = { 'UiPath': 'https://www.uipath.com/', 'testRigor': 'https://testrigor.com/', 'Tricentis Tosca': 'https://www.tricentis.com/products/automate-continuous-testing-tosca', 'Tricentis Testim': 'https://www.tricentis.com/products/testim', 'OpenText UFT One': 'https://www.opentext.com/products/uft-one', 'Keysight Eggplant': 'https://www.keysight.com/us/en/product/eggplant.html', 'QA Wolf': 'https://www.qawolf.com/' }
export const competitors: Competitor[] = grouped.flatMap(([category, names]) => names.map((name) => ({ name, category, focus: category === 'Developer-first market signals' ? 'Market-signal framework' : 'Test automation', website: slugs[name] || `https://${name.toLowerCase().replaceAll(' ', '').replaceAll('.', '')}.com/`, changed: 0, sourceHealth: 'Not checked' })))

export const releaseItems: ReleaseItem[] = [
  { id: 'wd-agent-passport', platform: 'Workday', title: 'Workday Launches Agent Passport to Test, Verify, and Continuously Monitor Every AI Agent in the Enterprise', family: 'Early access H2 2026; GA projected before end of 2026', publishedAt: '2026-06-02', firstDetectedAt: '2026-08-01', lastVerifiedAt: '2026-08-01', category: 'AI announcement', summary: 'Workday announced Agent Passport for testing, verifying, and continuously monitoring Workday-built and third-party AI agents.', changes: 'Agent testing attestations and runtime monitoring are described; availability is early access, not a Workday application release.', impact: 'Inference: teams using Workday agent workflows may need coverage for agent approvals, policy enforcement, and runtime exception paths.', areas: 'AI agents, HR, finance, IT', confidence: 98, evidenceStatus: 'Verified official source', sourceName: 'Workday Newsroom', sourceUrl: 'https://newsroom.workday.com/2026-06-02-Workday-Launches-Agent-Passport-to-Test%2C-Verify%2C-and-Continuously-Monitor-Every-AI-Agent-in-the-Enterprise', sourceHealth: 'Healthy' },
  { id: 'sn-australia', platform: 'ServiceNow', title: 'What’s New in the Australia Release', family: 'Australia', publishedAt: '2026-07-29', firstDetectedAt: '2026-08-01', lastVerifiedAt: '2026-08-01', category: 'Major release', summary: 'ServiceNow describes the Australia release as adding AI agents, platform governance, and workflow capabilities.', changes: 'Official page highlights AI Agent Studio, Process Mining, and governance changes.', impact: 'Inference: validate affected workflow, Now Assist, IntegrationHub, and UI regression paths in the target family.', areas: 'AI agents, workflows, governance', confidence: 91, evidenceStatus: 'Verified official source', sourceName: 'ServiceNow', sourceUrl: 'https://www.servicenow.com/platform/latest-release.html', sourceHealth: 'Healthy' },
  { id: 'sap-ux', platform: 'SAP SuccessFactors', title: 'SAP User Experience Updates Now Available in All Systems', family: '1H 2026', publishedAt: '2026-04-03', firstDetectedAt: '2026-08-01', lastVerifiedAt: '2026-08-01', category: 'User-interface change', summary: 'SAP states that user-experience updates previously available in Preview are available in Production and Preview systems.', changes: 'Shell bar, navigation menu, search, notifications, user menu, and settings are affected.', impact: 'Inference: revalidate navigation and selector baselines before broadening production regression coverage.', areas: 'Platform UX, navigation, notifications', confidence: 96, evidenceStatus: 'Verified official source', sourceName: 'SAP Help Portal', sourceUrl: 'https://help.sap.com/docs/successfactors-release-information/8e0d540f96474717bbf18df51e54e522/458a7525490f4848a71f9ee562ecefcd.html', sourceHealth: 'Healthy' },
]

export const insights: Insight[] = [
  ...releaseItems.map((item) => ({ id: item.id, subject: item.platform, subjectType: 'Enterprise Application' as const, category: item.category, headline: item.title, fact: item.summary, inference: item.impact, recommendation: 'Review the official evidence, identify affected tenant workflows, and validate in an approved non-production environment.', sourceName: item.sourceName, sourceUrl: item.sourceUrl, publishedAt: item.publishedAt, firstDetectedAt: item.firstDetectedAt, lastVerifiedAt: item.lastVerifiedAt, confidence: item.confidence, evidenceStatus: item.evidenceStatus, capabilities: item.areas.split(', ') })),
  { id: 'functionize-studio', subject: 'Functionize', subjectType: 'Competitor', category: 'Feature update', headline: 'Meet Functionize Studio', fact: 'Functionize states that Functionize Studio is generally available and describes it as an adversarial agent for proving software quality at agent speed.', inference: 'Inference: assess whether Studio changes Functionize’s agentic testing positioning or creates a differentiated evaluation workflow for enterprise buyers.', recommendation: 'Review the official announcement and validate the announced workflow, availability, and integration assumptions before changing competitive positioning.', sourceName: 'Functionize Blog', sourceUrl: 'https://www.functionize.com/blog/meet-functionize-studio', publishedAt: '2026-07-16', firstDetectedAt: '2026-08-02', lastVerifiedAt: '2026-08-02', confidence: 96, evidenceStatus: 'Verified official source', capabilities: ['Agentic testing', 'Quality evaluation'] },
]

export const matrix = [
  ['Natural-language test creation', 'Requires official-source verification', 'Requires official-source verification', 'Requires official-source verification'],
  ['Workday', 'No verified update in selected period', 'No verified update in selected period', 'No verified update in selected period'],
  ['Self-healing selectors', 'Requires official-source verification', 'Requires official-source verification', 'No verified update in selected period'],
  ['GitHub Actions', 'Requires official-source verification', 'Requires official-source verification', 'Requires official-source verification'],
]
