export type Signal = { id: string; vendor: string; title: string; category: string; date: string; confidence: number; status: string; score: number; excerpt: string }
export type Competitor = { name: string; category: string; focus: string; website: string; changed: number; sourceHealth: 'Healthy' | 'Not checked' }
export type Insight = { id: string; subject: string; subjectType: 'Enterprise Application' | 'Competitor'; category: string; headline: string; fact: string; inference: string; recommendation: string; sourceName: string; sourceUrl: string; publishedAt: string; firstDetectedAt: string; lastVerifiedAt: string; confidence: number; evidenceStatus: string; capabilities: string[] }
export type ReleaseItem = { id: string; platform: 'Workday' | 'ServiceNow' | 'SAP SuccessFactors' | 'Coupa'; title: string; family: string; publishedAt: string; firstDetectedAt: string; lastVerifiedAt: string; category: string; summary: string; changes: string; impact: string; areas: string; confidence: number; evidenceStatus: string; sourceName: string; sourceUrl: string; sourceHealth: string }

export const signals: Signal[] = [
  { id: 'sig-001', vendor: 'NovaTest', title: 'Announced guided AI test planning', category: 'New AI capability', date: '2026-07-30', confidence: 92, status: 'Synthetic demo evidence', score: 88, excerpt: 'Synthetic release note describes guided test-plan generation with human review.' },
  { id: 'sig-002', vendor: 'VerityQA', title: 'Added synthetic Workday coverage', category: 'New ERP support', date: '2026-07-27', confidence: 84, status: 'Synthetic demo evidence', score: 81, excerpt: 'Synthetic documentation now lists Workday among enterprise application examples.' },
  { id: 'sig-003', vendor: 'OrbitSpec', title: 'Changed trial messaging', category: 'Trial change', date: '2026-07-24', confidence: 68, status: 'Synthetic demo evidence', score: 56, excerpt: 'Synthetic pricing page changed from “start free” to “request access”.' },
  { id: 'sig-004', vendor: 'NovaTest', title: 'Published CI workflow connector', category: 'New integration', date: '2026-07-21', confidence: 89, status: 'Synthetic demo evidence', score: 76, excerpt: 'Synthetic integration guide describes pipeline-result artifacts.' },
]

export type RecentCompetitorUpdate = { id: string; vendor: string; category: string; date: string; title: string; summary: string; whyItMatters: string; recommendation: string; confidence: number; sourceName: string; sourceUrl: string; evidenceStatus: string }

// Official competitor publications only. These entries are deliberately kept
// separate from synthetic demo data and link directly to the publisher.
export const recentCompetitorUpdates: RecentCompetitorUpdate[] = [
  { id: 'functionize-studio', vendor: 'Functionize', category: 'Product release', date: '2026-07-16', title: 'Functionize Studio is generally available', summary: 'Functionize launched Studio, an adversarial AI agent designed to evaluate software quality. In practical terms, it is positioned to challenge an application and report whether it behaves as intended—not simply create a test case.', whyItMatters: 'This expands Functionize’s public story from automated test execution toward AI-led quality evaluation, which may matter to buyers comparing agentic testing approaches.', recommendation: 'Check the announced Studio workflow, availability, integrations, and evidence of results against your own product position.', confidence: 96, sourceName: 'Functionize official blog', sourceUrl: 'https://www.functionize.com/blog/meet-functionize-studio', evidenceStatus: 'Verified official source' },
  { id: 'uipath-agents-july', vendor: 'UiPath', category: 'AI capability', date: '2026-07-24', title: 'New assignment criteria for agent escalations', summary: 'UiPath added more ways to route an agent escalation: by workload, assigned group, round-robin distribution, or an LLM’s interpretation of the request. This gives teams more control over which person or queue receives an exception.', whyItMatters: 'It extends UiPath’s agent orchestration story beyond automation execution into operational hand-off and exception management.', recommendation: 'Review whether the new routing options are available in your target UiPath plan and compare them with your own exception-handling workflow.', confidence: 95, sourceName: 'UiPath Agents release notes', sourceUrl: 'https://docs.uipath.com/agents/automation-cloud/latest/release-notes/july-2026', evidenceStatus: 'Verified official source' },
  { id: 'smartbear-testcomplete', vendor: 'SmartBear TestComplete', category: 'Product release', date: '2026-07-08', title: 'TestComplete 15.83 is available', summary: 'SmartBear released TestComplete 15.83 with fixes and improvements around object recognition, recording reliability, CefSharp browser compatibility, and stability. These updates target the reliability of creating and running UI tests.', whyItMatters: 'Object recognition and recording reliability are core user experience points for UI-test creation, so this is a meaningful product-quality update for a direct test-automation alternative.', recommendation: 'Review the release notes for the supported technologies and assess whether the improvements address customer pain points relevant to your roadmap.', confidence: 94, sourceName: 'SmartBear TestComplete release notes', sourceUrl: 'https://support.smartbear.com/testcomplete/docs/general-info/whats-new.html', evidenceStatus: 'Verified official source' },
  { id: 'tricentis-tosca', vendor: 'Tricentis', category: 'Product update', date: 'July 2026', title: 'Generate API messages with a prompt', summary: 'Tricentis added prompt-based API-message generation to Tosca Cloud through MCP. A tester can describe the API message they need in natural language, which can reduce manual message construction during API test design.', whyItMatters: 'It brings natural-language assistance into API-test design, broadening Tosca’s AI-assisted testing narrative beyond UI automation.', recommendation: 'Compare the prompt-to-message workflow with your API-test authoring experience and confirm the MCP integration scope.', confidence: 93, sourceName: 'Tricentis Tosca Cloud release notes', sourceUrl: 'https://docs.tricentis.com/tosca-cloud/en-us/content/release_notes/release_notes.htm', evidenceStatus: 'Verified official source' },
  { id: 'opkey-workday-ai', vendor: 'Opkey', category: 'Official market update', date: '2026-07-09', title: 'Opkey published its view on AI-enabled Workday testing', summary: 'Opkey published a perspective on using AI for Workday and ERP lifecycle testing. This is a company positioning update, rather than evidence of a newly released product capability.', whyItMatters: 'It signals continued messaging around AI-driven ERP testing, but should be treated as positioning until a specific product release is verified.', recommendation: 'Track follow-up release notes or product documentation before treating this as a new competitive capability.', confidence: 88, sourceName: 'Opkey official blog', sourceUrl: 'https://www.opkey.com/blog/leveraging-ai-in-workday-testing-ensuring-quality-and-efficiency', evidenceStatus: 'Official publication — positioning claim' },
]

const grouped = [
  ['Direct competitors', ['Opkey', 'UiPath', 'Functionize', 'testRigor', 'Tricentis Tosca', 'Tricentis Testim']],
  ['Enterprise and ERP competitors', ['Worksoft', 'Leapwork', 'Panaya', 'Qualibrate', 'Provar', 'Copado Robotic Testing']],
  ['AI-native competitors', ['ACCELQ', 'Testsigma', 'mabl', 'KaneAI', 'Avo Automation', 'Autify', 'Momentic']],
  ['Testing infrastructure', ['BrowserStack', 'Sauce Labs', 'SmartBear TestComplete', 'OpenText UFT One', 'Ranorex', 'Perfecto', 'Kobiton', 'TestGrid', 'Keysight Eggplant', 'LambdaTest', 'Applitools']],
  ['Specialist platforms', ['Katalon', 'Virtuoso', 'Reflect', 'Rainforest QA', 'QA Wolf']],
  ['Developer-first market signals', ['Playwright', 'Cypress', 'Selenium', 'Appium', 'Puppeteer']],
] as const

const slugs: Record<string, string> = { 'UiPath': 'https://www.uipath.com/', 'testRigor': 'https://testrigor.com/', 'Tricentis Tosca': 'https://www.tricentis.com/products/automate-continuous-testing-tosca', 'Tricentis Testim': 'https://www.tricentis.com/products/testim', 'OpenText UFT One': 'https://www.opentext.com/products/uft-one', 'Keysight Eggplant': 'https://www.keysight.com/us/en/product/eggplant.html', 'QA Wolf': 'https://www.qawolf.com/' }
export const competitors: Competitor[] = grouped.flatMap(([category, names]) => names.map((name) => ({ name, category, focus: category === 'Developer-first market signals' ? 'Market-signal framework' : 'Test automation', website: slugs[name] || `https://${name.toLowerCase().replaceAll(' ', '').replaceAll('.', '')}.com/`, changed: 0, sourceHealth: 'Not checked' })))

export const releaseItems: ReleaseItem[] = [
  { id: 'wd-agent-passport', platform: 'Workday', title: 'Workday Launches Agent Passport to Test, Verify, and Continuously Monitor Every AI Agent in the Enterprise', family: 'Early access H2 2026; GA projected before end of 2026', publishedAt: '2026-06-02', firstDetectedAt: '2026-08-01', lastVerifiedAt: '2026-08-01', category: 'AI announcement', summary: 'Workday announced Agent Passport for testing, verifying, and continuously monitoring Workday-built and third-party AI agents.', changes: 'Documented change: agent testing attestations and runtime monitoring. This is not a general Workday tenant UI-release claim.', impact: 'Testing inference: review agent-approval, policy-enforcement, and runtime-exception business-process coverage before adopting the feature.', areas: 'AI agents, HR, finance, IT', confidence: 98, evidenceStatus: 'Verified official source', sourceName: 'Workday Newsroom', sourceUrl: 'https://newsroom.workday.com/2026-06-02-Workday-Launches-Agent-Passport-to-Test%2C-Verify%2C-and-Continuously-Monitor-Every-AI-Agent-in-the-Enterprise', sourceHealth: 'Healthy' },
  { id: 'sn-australia', platform: 'ServiceNow', title: 'What’s New in the Australia Release', family: 'Australia', publishedAt: '2026-05-05', firstDetectedAt: '2026-08-01', lastVerifiedAt: '2026-08-01', category: 'Major platform release', summary: 'ServiceNow’s Australia release adds AI agents, Process Mining, AI Agent Studio, Intelligent Approvals, and governance capabilities.', changes: 'Documented change: workflow automation and approval paths can include new AI-agent and governance capabilities; customers should review release notes for their upgrade path.', impact: 'Testing inference: run upgrade regression for affected workflows, approvals, Now Assist, IntegrationHub, custom UI actions, and ATF coverage. Do not assume selectors changed without observing the authorized instance.', areas: 'Workflows, approvals, AI agents, governance', confidence: 91, evidenceStatus: 'Verified official source', sourceName: 'ServiceNow Australia release', sourceUrl: 'https://www.servicenow.com/docs/r/release-notes/rn-learn-landing-page.html', sourceHealth: 'Healthy' },
  { id: 'sap-ux', platform: 'SAP SuccessFactors', title: 'SAP User Experience Updates Now Available in All Systems', family: '1H 2026', publishedAt: '2026-04-03', firstDetectedAt: '2026-08-01', lastVerifiedAt: '2026-08-01', category: 'Documented user-interface change', summary: 'SAP states that user-experience updates are available in Production and Preview systems.', changes: 'Documented change: shell bar, navigation menu, people/action search, notifications, user menu, settings, and some navigation behavior change. SAP explicitly notes that automated test scripts may need updating.', impact: 'Testing inference: prioritize navigation, search, notification, user-menu, and home-page selector baselines in a non-production tenant before rollout.', areas: 'Platform UX, navigation, search, notifications', confidence: 96, evidenceStatus: 'Verified official source', sourceName: 'SAP Help Portal', sourceUrl: 'https://help.sap.com/docs/successfactors-release-information/8e0d540f96474717bbf18df51e54e522/458a7525490f4848a71f9ee562ecefcd.html', sourceHealth: 'Healthy' },
  { id: 'coupa-csp-45-5', platform: 'Coupa', title: 'Coupa Supplier Portal 45.5 release', family: 'CSP 45.5', publishedAt: '2026-07-16', firstDetectedAt: '2026-08-02', lastVerifiedAt: '2026-08-02', category: 'Supplier portal release', summary: 'Coupa documents CSP 45.5 enhancements for new-supplier onboarding and invoice API workflows.', changes: 'Documented change: AI-powered profile prefilling during supplier onboarding; invoice API OAuth2 support and invoice-creation controls were also added.', impact: 'Testing inference: validate supplier registration, sign-in/onboarding field states, invoice-creation permissions, and API authentication flows. Selector impact requires confirmation in an authorized CSP environment.', areas: 'Supplier onboarding, sign-in, invoicing, API', confidence: 95, evidenceStatus: 'Verified official source', sourceName: 'Coupa Supplier Portal release notes', sourceUrl: 'https://docs.coupa.com/en/supplier-documentation/coupa-for-suppliers/announcements-and-general-information/coupa-supplier-portal-release-notes', sourceHealth: 'Healthy' },
]

export const insights: Insight[] = [
  ...releaseItems.map((item) => ({ id: item.id, subject: item.platform, subjectType: 'Enterprise Application' as const, category: item.category, headline: item.title, fact: item.summary, inference: item.impact, recommendation: 'Review the official evidence, identify affected tenant workflows, and validate in an approved non-production environment.', sourceName: item.sourceName, sourceUrl: item.sourceUrl, publishedAt: item.publishedAt, firstDetectedAt: item.firstDetectedAt, lastVerifiedAt: item.lastVerifiedAt, confidence: item.confidence, evidenceStatus: item.evidenceStatus, capabilities: item.areas.split(', ') })),
  ...recentCompetitorUpdates.map((item) => ({ id: item.id, subject: item.vendor, subjectType: 'Competitor' as const, category: item.category, headline: item.title, fact: item.summary, inference: item.whyItMatters, recommendation: item.recommendation, sourceName: item.sourceName, sourceUrl: item.sourceUrl, publishedAt: item.date, firstDetectedAt: '2026-08-02', lastVerifiedAt: '2026-08-02', confidence: item.confidence, evidenceStatus: item.evidenceStatus, capabilities: [item.category] })),
]

export const matrix = [
  ['Natural-language test creation', 'Requires official-source verification', 'Requires official-source verification', 'Requires official-source verification'],
  ['Workday', 'No verified update in selected period', 'No verified update in selected period', 'No verified update in selected period'],
  ['Self-healing selectors', 'Requires official-source verification', 'Requires official-source verification', 'No verified update in selected period'],
  ['GitHub Actions', 'Requires official-source verification', 'Requires official-source verification', 'Requires official-source verification'],
]
